# GRU model parameters
gru_input_dim: 200          # Word embedding dimension
gru_hidden_dim: 50          # GRU output dimension per word
gru_bidirectional: true     # Use a bidirectional GRU
gru_output_dim: 100         # Word/sentence annotation dimension (forward + backward)
gru_num_layers: 1           # Number of GRU layers
frozen_attention: true     # Freeze attention weights during training

# Word embedding parameters
word_embedding_dim: 200                # Word embedding dimension
word_embedding_min_frequency: 5        # Minimum frequency for words to be included in the vocabulary

# Batch parameters
batch_size: 64            # Batch size

# Training parameters
optimizer_type: "SGD"             # Optimizer type
optimizer_momentum: 0.9           # Momentum for the SGD optimizer
epochs: 50                        # Number of epochs
dataset: sst2                     # Dataset to use


# Context vector initialization
context_vectors_dim: 100                  # Dimension of word/sentence context vectors

# Dataset parameters
num_classes: 2            # Number of classes